# Generated by Django 4.1.5 on 2023-01-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinsung', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('파리,파리나방 채집', '파리,파리나방 채집'), ('수고,경사각,방위측정', '수고,경사각,방위측정'), ('수목 직경측정', '수목 직경측정'), ('수목 연륜측정 및 분석', '수목 연륜측정 및 분석'), ('수목 기타측정 및 진단', '수목 기타측정 및 진단'), ('야외조사 보조용품', '야외조사 보조용품'), ('곤충 채집', '곤충 채집'), ('곤충 분류,전시,보관', '곤충 분류,전시,보관'), ('식물 채집,보관', '식물 채집,보관'), ('병해충 방제기구', '병해충 방제기구'), ('기타', '기타')], default=('기타', '기타'), max_length=30),
        ),
    ]
