# Generated by Django 4.1.5 on 2023-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinsung', '0003_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
